[build-system]
requires = ['setuptools>=61']
build-backend = 'setuptools.build_meta'

[project]
name = 'df-translate'
version = '0.1.0'
requires-python = '>=3.12'
dependencies = [
    'aiohttp==3.14.1',
    'aiohttp-retry==2.9.1',
    'pandas==3.0.3',
]

[project.optional-dependencies]
dev = ['pytest==9.1.1']

[tool.pytest.ini_options]
pythonpath = '.'
